# Generated by Django 4.2.1 on 2023-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_alter_content_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likelihood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
