# Generated by Django 4.2.1 on 2023-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_alter_content_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='relevance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
