# Generated by Django 4.2.1 on 2023-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_alter_content_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
